package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.Consumes;
import javax.ws.rs.PATCH;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AgeRatingDeclarationUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/ageRatingDeclarations/{id}")

public interface AgeRatingDeclarationsApi {

	/**
	 * Modify an Age Rating Declaration
	 *
	 * Provide age-related information so the App Store can determine the age rating
	 * for your app.
	 *
	 */
	@PATCH

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response modifyAgeRatingDeclaration(@PathParam("id") String id,
			AgeRatingDeclarationUpdateRequest ageRatingDeclarationUpdateRequest);
}
