package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppEventVideoClipCreateRequest;
import net.odyssi.asc4j.model.AppEventVideoClipUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appEventVideoClips")

public interface AppEventVideoClipsApi {

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventVideoClipsCreateInstance(AppEventVideoClipCreateRequest appEventVideoClipCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventVideoClipsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventVideoClipsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appEventVideoClips]") List<String> fieldsAppEventVideoClips,
			@QueryParam("include") List<String> include);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventVideoClipsUpdateInstance(@PathParam("id") String id,
			AppEventVideoClipUpdateRequest appEventVideoClipUpdateRequest);
}
