package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppEventLocalizationCreateRequest;
import net.odyssi.asc4j.model.AppEventLocalizationUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appEventLocalizations")

public interface AppEventLocalizationsApi {

	@GET
	@Path("/{id}/appEventScreenshots")
	@Produces({ "application/json" })

	public Response appEventLocalizationsAppEventScreenshotsGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[appEventScreenshots]") List<String> fieldsAppEventScreenshots,
			@QueryParam("fields[appEventLocalizations]") List<String> fieldsAppEventLocalizations,
			@QueryParam("limit") Integer limit, @QueryParam("include") List<String> include);

	@GET
	@Path("/{id}/appEventVideoClips")
	@Produces({ "application/json" })

	public Response appEventLocalizationsAppEventVideoClipsGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[appEventVideoClips]") List<String> fieldsAppEventVideoClips,
			@QueryParam("fields[appEventLocalizations]") List<String> fieldsAppEventLocalizations,
			@QueryParam("limit") Integer limit, @QueryParam("include") List<String> include);

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventLocalizationsCreateInstance(
			AppEventLocalizationCreateRequest appEventLocalizationCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventLocalizationsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventLocalizationsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appEventLocalizations]") List<String> fieldsAppEventLocalizations,
			@QueryParam("include") List<String> include,
			@QueryParam("fields[appEventScreenshots]") List<String> fieldsAppEventScreenshots,
			@QueryParam("fields[appEventVideoClips]") List<String> fieldsAppEventVideoClips,
			@QueryParam("limit[appEventScreenshots]") Integer limitAppEventScreenshots,
			@QueryParam("limit[appEventVideoClips]") Integer limitAppEventVideoClips);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventLocalizationsUpdateInstance(@PathParam("id") String id,
			AppEventLocalizationUpdateRequest appEventLocalizationUpdateRequest);
}
