package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppEventScreenshotCreateRequest;
import net.odyssi.asc4j.model.AppEventScreenshotUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appEventScreenshots")

public interface AppEventScreenshotsApi {

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventScreenshotsCreateInstance(AppEventScreenshotCreateRequest appEventScreenshotCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventScreenshotsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appEventScreenshotsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appEventScreenshots]") List<String> fieldsAppEventScreenshots,
			@QueryParam("include") List<String> include);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appEventScreenshotsUpdateInstance(@PathParam("id") String id,
			AppEventScreenshotUpdateRequest appEventScreenshotUpdateRequest);
}
