package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppStoreVersionExperimentTreatmentLocalizationCreateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appStoreVersionExperimentTreatmentLocalizations")

public interface AppStoreVersionExperimentTreatmentLocalizationsApi {

	@GET
	@Path("/{id}/appPreviewSets")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentLocalizationsAppPreviewSetsGetToManyRelated(
			@PathParam("id") String id, @QueryParam("filter[previewType]") List<String> filterPreviewType,
			@QueryParam("filter[appCustomProductPageLocalization]") List<String> filterAppCustomProductPageLocalization,
			@QueryParam("filter[appStoreVersionLocalization]") List<String> filterAppStoreVersionLocalization,
			@QueryParam("fields[appCustomProductPageLocalizations]") List<String> fieldsAppCustomProductPageLocalizations,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("fields[appPreviews]") List<String> fieldsAppPreviews,
			@QueryParam("fields[appPreviewSets]") List<String> fieldsAppPreviewSets,
			@QueryParam("fields[appStoreVersionLocalizations]") List<String> fieldsAppStoreVersionLocalizations,
			@QueryParam("limit") Integer limit, @QueryParam("limit[appPreviews]") Integer limitAppPreviews,
			@QueryParam("include") List<String> include);

	@GET
	@Path("/{id}/appScreenshotSets")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentLocalizationsAppScreenshotSetsGetToManyRelated(
			@PathParam("id") String id,
			@QueryParam("filter[screenshotDisplayType]") List<String> filterScreenshotDisplayType,
			@QueryParam("filter[appCustomProductPageLocalization]") List<String> filterAppCustomProductPageLocalization,
			@QueryParam("filter[appStoreVersionLocalization]") List<String> filterAppStoreVersionLocalization,
			@QueryParam("fields[appScreenshotSets]") List<String> fieldsAppScreenshotSets,
			@QueryParam("fields[appCustomProductPageLocalizations]") List<String> fieldsAppCustomProductPageLocalizations,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("fields[appScreenshots]") List<String> fieldsAppScreenshots,
			@QueryParam("fields[appStoreVersionLocalizations]") List<String> fieldsAppStoreVersionLocalizations,
			@QueryParam("limit") Integer limit, @QueryParam("limit[appScreenshots]") Integer limitAppScreenshots,
			@QueryParam("include") List<String> include);

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentLocalizationsCreateInstance(
			AppStoreVersionExperimentTreatmentLocalizationCreateRequest appStoreVersionExperimentTreatmentLocalizationCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentLocalizationsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentLocalizationsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("include") List<String> include,
			@QueryParam("fields[appScreenshotSets]") List<String> fieldsAppScreenshotSets,
			@QueryParam("fields[appPreviewSets]") List<String> fieldsAppPreviewSets,
			@QueryParam("limit[appPreviewSets]") Integer limitAppPreviewSets,
			@QueryParam("limit[appScreenshotSets]") Integer limitAppScreenshotSets);
}
