package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppStoreVersionPromotionCreateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appStoreVersionPromotions")

public interface AppStoreVersionPromotionsApi {

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionPromotionsCreateInstance(
			AppStoreVersionPromotionCreateRequest appStoreVersionPromotionCreateRequest);
}
