package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppStoreVersionExperimentCreateRequest;
import net.odyssi.asc4j.model.AppStoreVersionExperimentUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appStoreVersionExperiments")

public interface AppStoreVersionExperimentsApi {

	@GET
	@Path("/{id}/appStoreVersionExperimentTreatments")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentsAppStoreVersionExperimentTreatmentsGetToManyRelated(
			@PathParam("id") String id,
			@QueryParam("fields[appStoreVersionExperiments]") List<String> fieldsAppStoreVersionExperiments,
			@QueryParam("fields[appStoreVersionExperimentTreatments]") List<String> fieldsAppStoreVersionExperimentTreatments,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("limit") Integer limit,
			@QueryParam("limit[appStoreVersionExperimentTreatmentLocalizations]") Integer limitAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("include") List<String> include);

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentsCreateInstance(
			AppStoreVersionExperimentCreateRequest appStoreVersionExperimentCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appStoreVersionExperiments]") List<String> fieldsAppStoreVersionExperiments,
			@QueryParam("include") List<String> include,
			@QueryParam("fields[appStoreVersionExperimentTreatments]") List<String> fieldsAppStoreVersionExperimentTreatments,
			@QueryParam("limit[appStoreVersionExperimentTreatments]") Integer limitAppStoreVersionExperimentTreatments);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentsUpdateInstance(@PathParam("id") String id,
			AppStoreVersionExperimentUpdateRequest appStoreVersionExperimentUpdateRequest);
}
