package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppStoreVersionExperimentTreatmentCreateRequest;
import net.odyssi.asc4j.model.AppStoreVersionExperimentTreatmentUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appStoreVersionExperimentTreatments")

public interface AppStoreVersionExperimentTreatmentsApi {

	@GET
	@Path("/{id}/appStoreVersionExperimentTreatmentLocalizations")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentsAppStoreVersionExperimentTreatmentLocalizationsGetToManyRelated(
			@PathParam("id") String id, @QueryParam("filter[locale]") List<String> filterLocale,
			@QueryParam("fields[appScreenshotSets]") List<String> fieldsAppScreenshotSets,
			@QueryParam("fields[appStoreVersionExperimentTreatments]") List<String> fieldsAppStoreVersionExperimentTreatments,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("fields[appPreviewSets]") List<String> fieldsAppPreviewSets, @QueryParam("limit") Integer limit,
			@QueryParam("limit[appScreenshotSets]") Integer limitAppScreenshotSets,
			@QueryParam("limit[appPreviewSets]") Integer limitAppPreviewSets,
			@QueryParam("include") List<String> include);

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentsCreateInstance(
			AppStoreVersionExperimentTreatmentCreateRequest appStoreVersionExperimentTreatmentCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentsDeleteInstance(@PathParam("id") String id);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[appStoreVersionExperimentTreatments]") List<String> fieldsAppStoreVersionExperimentTreatments,
			@QueryParam("include") List<String> include,
			@QueryParam("fields[appStoreVersionExperimentTreatmentLocalizations]") List<String> fieldsAppStoreVersionExperimentTreatmentLocalizations,
			@QueryParam("limit[appStoreVersionExperimentTreatmentLocalizations]") Integer limitAppStoreVersionExperimentTreatmentLocalizations);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response appStoreVersionExperimentTreatmentsUpdateInstance(@PathParam("id") String id,
			AppStoreVersionExperimentTreatmentUpdateRequest appStoreVersionExperimentTreatmentUpdateRequest);
}
