package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.AppStoreVersionReleaseRequestCreateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/appStoreVersionReleaseRequests")

public interface AppStoreVersionReleaseRequestsApi {

	/**
	 * Manually Release an App Store Approved Version of Your App
	 *
	 * Release an approved version of your app to the App Store.
	 *
	 */
	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response releaseAppStoreApprovedVersion(
			AppStoreVersionReleaseRequestCreateRequest appStoreVersionReleaseRequestCreateRequest);
}
