package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.BuildBetaNotificationCreateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/buildBetaNotifications")

public interface BuildBetaNotificationsApi {

	/**
	 * Send Notification of an Available Build
	 *
	 * Send a notification to all assigned beta testers that a build is available
	 * for testing.
	 *
	 */
	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response sendBetaBuildNotification(BuildBetaNotificationCreateRequest buildBetaNotificationCreateRequest);
}
