package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/ciBuildActions/{id}")

public interface CiBuildActionsApi {

	@GET
	@Path("/artifacts")
	@Produces({ "application/json" })

	public Response ciBuildActionsArtifactsGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[ciArtifacts]") List<String> fieldsCiArtifacts, @QueryParam("limit") Integer limit);

	@GET
	@Path("/buildRun")
	@Produces({ "application/json" })

	public Response ciBuildActionsBuildRunGetToOneRelated(@PathParam("id") String id,
			@QueryParam("fields[scmGitReferences]") List<String> fieldsScmGitReferences,
			@QueryParam("fields[ciBuildRuns]") List<String> fieldsCiBuildRuns,
			@QueryParam("fields[ciWorkflows]") List<String> fieldsCiWorkflows,
			@QueryParam("fields[scmPullRequests]") List<String> fieldsScmPullRequests,
			@QueryParam("fields[ciProducts]") List<String> fieldsCiProducts,
			@QueryParam("fields[builds]") List<String> fieldsBuilds, @QueryParam("limit[builds]") Integer limitBuilds,
			@QueryParam("include") List<String> include);

	@GET

	@Produces({ "application/json" })

	public Response ciBuildActionsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[ciBuildActions]") List<String> fieldsCiBuildActions,
			@QueryParam("include") List<String> include, @QueryParam("fields[ciIssues]") List<String> fieldsCiIssues,
			@QueryParam("fields[ciBuildRuns]") List<String> fieldsCiBuildRuns,
			@QueryParam("fields[ciTestResults]") List<String> fieldsCiTestResults,
			@QueryParam("fields[ciArtifacts]") List<String> fieldsCiArtifacts);

	@GET
	@Path("/issues")
	@Produces({ "application/json" })

	public Response ciBuildActionsIssuesGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[ciIssues]") List<String> fieldsCiIssues, @QueryParam("limit") Integer limit);

	@GET
	@Path("/testResults")
	@Produces({ "application/json" })

	public Response ciBuildActionsTestResultsGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[ciTestResults]") List<String> fieldsCiTestResults, @QueryParam("limit") Integer limit);
}
