package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/diagnosticSignatures/{id}/logs")

public interface DiagnosticSignaturesApi {

	/**
	 * Download Logs for a Diagnostic Signature
	 *
	 * Get the anonymized backtrace logs associated with a specific diagnostic
	 * signature.
	 *
	 */
	@GET

	@Produces({ "application/vnd.apple.xcode-metrics+json", "application/json" })

	public Response downloadDiagnosticSignatureLogs(@PathParam("id") String id, @QueryParam("limit") Integer limit);
}
