package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/inAppPurchases/{id}")

public interface InAppPurchasesApi {

	/**
	 * Read In-App Purchase Information
	 *
	 * Get information about an in-app purchase.
	 *
	 */
	@GET

	@Produces({ "application/json" })

	public Response readInAppPurchaseInformation(@PathParam("id") String id,
			@QueryParam("fields[inAppPurchases]") List<String> fieldsInAppPurchases,
			@QueryParam("include") List<String> include, @QueryParam("limit[apps]") Integer limitApps);
}
