package net.odyssi.asc4j.jaxrs;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.ReviewSubmissionCreateRequest;
import net.odyssi.asc4j.model.ReviewSubmissionUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/reviewSubmissions")

public interface ReviewSubmissionsApi {

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response reviewSubmissionsCreateInstance(ReviewSubmissionCreateRequest reviewSubmissionCreateRequest);

	@GET

	@Produces({ "application/json" })

	public Response reviewSubmissionsGetCollection(@QueryParam("filter[app]") List<String> filterApp,
			@QueryParam("filter[platform]") List<String> filterPlatform,
			@QueryParam("filter[state]") List<String> filterState,
			@QueryParam("fields[reviewSubmissions]") List<String> fieldsReviewSubmissions,
			@QueryParam("limit") Integer limit, @QueryParam("include") List<String> include,
			@QueryParam("fields[reviewSubmissionItems]") List<String> fieldsReviewSubmissionItems,
			@QueryParam("limit[items]") Integer limitItems);

	@GET
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response reviewSubmissionsGetInstance(@PathParam("id") String id,
			@QueryParam("fields[reviewSubmissions]") List<String> fieldsReviewSubmissions,
			@QueryParam("include") List<String> include,
			@QueryParam("fields[reviewSubmissionItems]") List<String> fieldsReviewSubmissionItems,
			@QueryParam("limit[items]") Integer limitItems);

	@GET
	@Path("/{id}/items")
	@Produces({ "application/json" })

	public Response reviewSubmissionsItemsGetToManyRelated(@PathParam("id") String id,
			@QueryParam("fields[appStoreVersionExperiments]") List<String> fieldsAppStoreVersionExperiments,
			@QueryParam("fields[reviewSubmissionItems]") List<String> fieldsReviewSubmissionItems,
			@QueryParam("fields[appStoreVersions]") List<String> fieldsAppStoreVersions,
			@QueryParam("fields[appCustomProductPageVersions]") List<String> fieldsAppCustomProductPageVersions,
			@QueryParam("fields[appEvents]") List<String> fieldsAppEvents, @QueryParam("limit") Integer limit,
			@QueryParam("include") List<String> include);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response reviewSubmissionsUpdateInstance(@PathParam("id") String id,
			ReviewSubmissionUpdateRequest reviewSubmissionUpdateRequest);
}
