package net.odyssi.asc4j.jaxrs;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.PATCH;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import net.odyssi.asc4j.model.ReviewSubmissionItemCreateRequest;
import net.odyssi.asc4j.model.ReviewSubmissionItemUpdateRequest;

/**
 * App Store Connect API (Enhanced)
 *
 * <p>
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 */
@Path("/v1/reviewSubmissionItems")

public interface ReviewSubmissionItemsApi {

	@POST

	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response reviewSubmissionItemsCreateInstance(
			ReviewSubmissionItemCreateRequest reviewSubmissionItemCreateRequest);

	@DELETE
	@Path("/{id}")
	@Produces({ "application/json" })

	public Response reviewSubmissionItemsDeleteInstance(@PathParam("id") String id);

	@PATCH
	@Path("/{id}")
	@Consumes({ "application/json" })
	@Produces({ "application/json" })

	public Response reviewSubmissionItemsUpdateInstance(@PathParam("id") String id,
			ReviewSubmissionItemUpdateRequest reviewSubmissionItemUpdateRequest);
}
